### ISSUE TITLE
invoke to call the server methods

### ISSUE THREAD

**Issue by zdh8675** [DVLP/signalr-no-jquery#18]
![image](https://cloud.githubusercontent.com/assets/5927453/25473258/56f249d4-2b61-11e7-89a9-da7b58db2cda.png)

I have already specified here { jsonp: true }, 

and then use this code to call the server method:

`hubProxy.invoke('joinGroupAsync', { groupName: 'GroupBaoJing' })`

but reported the following error:

![image](https://cloud.githubusercontent.com/assets/5927453/25473440/10a48c98-2b62-11e7-924e-1bafa557e584.png)

I used C # to write Signalr's self-hosted service, and also added the code to allow cross-domain, but it did not work.

So，I really do not know how to solve this problem, ask for you help.

**Comment by zdh8675** [comment]
Everyone has not encountered any problems about invoke?

**Comment by gtwilliams03** [comment]
I have and I think it might be limited to long polling.  I had to add this line at line 73 of jQueryShim.js:

```
if (options.type === 'GET' && options.data.data) options.url += `&data=${options.data.data}`
```

Can you try that and see if it works for you?  When the POST command switches to a GET in long polling, the post body is ignored and you have to put the data into the querystring. (I think)

**Comment by zdh8675** [comment]
@gtwilliams03
thank you sir, the error disappear, but I still have problems, it seems that there is no call to the server method.

![image](https://cloud.githubusercontent.com/assets/5927453/25731509/821c9826-3179-11e7-91cc-2b39fdeb3146.png)

I can not see any 'Console', method not called, something goes wrong?

**Comment by kamil212** [comment]
I'm seeing the same error as the original post, as I try to invoke a subscription :(

Edit: Disabled { jsonp: true } and I'm all good now

**Comment by taylormichels** [comment]
thanks @kamil212 that solved the same issue for me too
