### ISSUE TITLE
Still getting window is not defined error : referenced with node_modules/signalr-no-jquery/build/signalR.js

### ISSUE THREAD

**Issue by Vinutha-BK** [DVLP/signalr-no-jquery#22]
﻿Hi,
I would like use the signal r with worker , as web worker doesn't support window object .I tried installing signalr-no-jquery. but still getting below error.

signalR.js:987 Uncaught ReferenceError: window is not defined
./node_modules/signalr-no-jquery/build/signalR.js	@	signalR.js:987
__webpack_require__	@	bootstrap c25ea15…:19
./src/app/Service/ServerCommunication/WebSocketCommunication.js	@	c25ea15….worker.js:3895
__webpack_require__	@	bootstrap c25ea15…:19
./node_modules/source-map-loader/index.js!./src/app/Service/ServerCommunication/index.js	@	index.js:1
__webpack_require__

**Comment by DuBistKomisch** [comment]
https://github.com/ViviRnD/signalr-node/commit/4086998c486a52e8cd972110487f3e0dc3a9de4e and probably a little bit of https://github.com/ViviRnD/signalr-node/commit/0571a28855d98febfbfb25853cbe433280077cf6 from my fork should get rid of all references to `window`.
