### ISSUE TITLE
Error: You are using a version of the client that isn't compatible with the server

### ISSUE THREAD

**Issue by doreentseng** [DVLP/signalr-no-jquery#24]
I'm using signalr-no-jquery with reactJS.
It shows the exception "Error: You are using a version of the client that isn't compatible with the server.  Client version 1.5, server version 1.4." but when I use signalR without signalr-no-jquery in jquery, it works fine.

How do I deal with it?

**Comment by DVLP** [comment]
Interesting. Is that an error coming from the server and displayed by client or is it generated by client?

**Comment by doreentseng** [comment]
@DVLP It's from the server and displayed by client. In connection.fail(function(reason){}).

**Comment by DVLP** [comment]
Can't you update singlar version on the server?

**Comment by sorenhoyer** [comment]
Same error here: doesn't work for the latest Microsoft.AspNetCore.SignalR v.1.0.0-alpha2-final

However  this works fine: [https://github.com/aspnet/SignalR](https://github.com/aspnet/SignalR)
