### ISSUE TITLE
Server-side Pre-rendering (ssr, angular universal) fails because of reference to window

### ISSUE THREAD

**Issue by JohnGalt1717** [DVLP/signalr-no-jquery#25]
signalR.js assumes "window" exists. Could you put in a fix that at the top of that file did 
if (typeof window !== 'undefined') {
<file here>
}

Then this will work for React and Angular amongst others with SSR enabled.

**Comment by fzh5201413** [comment]
// vue nuxt.js  
async beforeMount() {
   // import in Browser 
    const { hubConnection } = await import('signalr-no-jquery')
}
