### ISSUE TITLE
Error in connecting via WebSocket 

### ISSUE THREAD

**Issue by suraj18** [DVLP/signalr-no-jquery#32]
Hi,
I' m facing issue :Error during WebSocket handshake: Unexpected response code: 400 while connecting to Hub. And again it fall down to serverSentEvents and works fine. What could be the reason with transport :WebSocket

**Comment by misumi111** [comment]
Hi，I have the same problem.
I find it is on line 748 and 754 in src/signalR.js.

```javascript
        if ($.inArray(transport, supportedTransports) >= 0) {
```

```javascript
        } else if ($.inArray(config.transport, supportedTransports) >= 0) {
```


$.inArray is from jQueryShim.js
```javascript
    inArray: (arr,item) => arr.indexOf(item) !== -1
```
This is return Boolean. So I resolve this problem.
```javascript
        if ($.inArray(supportedTransports, transport)) {
```

```javascript
        } else if ($.inArray(supportedTransports, config.transport)) {
```

**Comment by dcyuksel** [comment]
still having this issue

**Comment by tubalmartin** [comment]
@misumi111 make a PR please with the fixes
