### ISSUE TITLE
call function ionic: this.refreshData is not a function

### ISSUE THREAD

**Issue by enriquehernandez** [DVLP/signalr-no-jquery#34]
My code
hubProxy.on('broadcastExisteCambioDatos', function (message) {
      console.log('hubConnection', message);
      this.refreshData();
    });

.....
refreshData() {
....
}

Error:
ERROR TypeError: this.refreshData is not a function

**Comment by DVLP** [comment]
this error is not related to this library. You should post your problem on stackoverflow
maybe use arrow function to  bind `this` to the object you're in
```javascript
hubProxy.on('broadcastExisteCambioDatos', (message) => {
console.log('hubConnection', message);
this.refreshData();
});
```
