### ISSUE TITLE
Rush messages

### ISSUE THREAD

**Issue by rolivares** [DVLP/signalr-no-jquery#39]
Does Is there some restriction relative on flood messages? 

I'm trying to send sucesive mesages to the client on same message method but diferent payload and only the first message is being proceced on client. 

When I force the process to delay 1 second between messages all messages are proceced and received by client.

**Comment by jherman** [comment]
I get this too.  I believe its this library.  It's not stable it appears.  I've opened several browser windows, and i get mismatch of one that some through and ones that don't.  When I create a listener on the server side, they all come through normally - leading me to believe something is wrong with library.
