### ISSUE TITLE
examples ?

### ISSUE THREAD

**Issue by hypo-thesis** [DVLP/signalr-no-jquery#48]
Any react example in which it fetched some data from signalr server ? I would appreciate it.

I don't know where to put my request as such : 

{
 "H":"quotessubscribehub",
 "M":"getLastPrices",
 "A":[["BTCUSD","LTCUSD","ETHUSD","TLRY.US","GWPH.US"]],
 "I":0
}

**Comment by DVLP** [comment]
The client-side is the same as regular SignalR (non-.NET version) and covered in it's documentation
