### ISSUE TITLE
typescript docs incorrect

### ISSUE THREAD

**Issue by gregveres** [DVLP/signalr-no-jquery#49]
Thank you for providing this!

I just spent a few hours trying to get this to compile under typescript. When I was about to give up and create my own typings file for the module, I decided to check definitely typed to see if one was there. And sure enough somebody had already built a typings file for signalr-no-types. 

So I would recommend that you update the main readme file to indicate that you just need to npm -D install @types/signalr-no-jquery

that will give you the types that you need.

**Comment by DVLP** [comment]
Added in Readme
