### ISSUE TITLE
Using with Angular2

### ISSUE THREAD

**Issue by AbrarJahin** [DVLP/signalr-no-jquery#5]
Hi, I like to use it with Angular2.

Is there any way of doing that?

Is there any example from which I can see demo code for that?

Thanks

**Comment by sateffen** [comment]
Yould you specify, what problem you've got with the integration in angular2?

The usual way of integrating this lib in angular2 would be to implement one service for managing the connection and a couple of other services, using the first one and providing the different hubs.

Maybe I've got some sparetime at some weekend to build a little example gist, without angular2 integration, but giving an idea of how to use signalR.

**Comment by AbrarJahin** [comment]
If you can give a example code, that would be great help.

Thanks @sateffen

**Comment by sateffen** [comment]
@AbrarJahin A basic example can be found [here](https://github.com/sateffen/jqueryless-signalr) in the readme. I'm currently testing an own version of a jqueryless signalr, which contains the correct signalr version (not on npm yet, nor tested anywhere).

You can use the code as it stands, just replace `const signalR = require('jqueryless-signalr');` with `const signalR = require('signalr-no-jquery').hubConnection;`

That might not be angular2 specific code, but adapting that one for an angular2 service should be trivial.

**Comment by ghost** [comment]
# **_This is an Example how to use is with angular 5:_** 

## SignalR Service

![image](https://user-images.githubusercontent.com/15155243/38668733-384612e0-3e4d-11e8-861c-3b1711a3e5a8.png)

## Environment 
![image](https://user-images.githubusercontent.com/15155243/38668868-8d87c33e-3e4d-11e8-9fa1-0f43e4a1e67f.png)

**Comment by AbrarJahin** [comment]
Thanks to you both
@sateffen @BissacM

**Comment by itsthetaste** [comment]
I also needed to add the types like this
`npm install --save @types/signalr-no-jquery`
and also I didn't need the new on the hubConnection
