### ISSUE TITLE
signalr code is many versions behind official release

### ISSUE THREAD

**Issue by gregveres** [DVLP/signalr-no-jquery#50]
@DVLP 
I was wondering why my client was only requesting protocol version 1.5 when the code I am replacing was requesting version 2.0. It is because signalr-no-jquery is using a quite old version of the official signalr code: v2.2.1. They are now on v2.4.1.

I have forked the project and upgraded the version of signalR to 2.4.1. I am creating this issue to give details of the pull request I am about to submit. I would greatly appreciate if you would update the npm package with the new version. 

To figure out what needed to be changed in v2.4.1, I first diff'd your version against the original v2.2.1 to see what changes you made. I then applied those same changes to v2.4.1 and I scanned for any other jquery use that might be new. There does not seem to be any new jquery use. 

I have used this version locally in my project and I am getting signalr messages transferring back and forth and now the client is trying to negotiate protocol version 2.1 (newest version).

I also updated the ReadMe file to incorporate the other outstanding PR and to improve the docs around how to use this with Typescript. Somebody created a definitely typed package for this package so I referenced it.

**Comment by gregveres** [comment]
I have closed PR #51 because it is now obsolete based on PR #52.

**Comment by e965** [comment]
Because @erzki (author of PR #52) disappeared somewhere, I made my own fork from the project with some improvements (and with the updated SignalR, of course).

enjoy https://github.com/cojamru/signalr-no-jquery
