### ISSUE TITLE
Update signalR to latest version

### ISSUE THREAD

**Issue by MichalK6677** [DVLP/signalr-no-jquery#61]
It's related to signalR connection fails with Chrome 88 and newer:
https://github.com/SignalR/SignalR/issues/4536

This repo needs to be updated to avoid that issue.

**Comment by oleksandrbabin** [comment]
Does any estimates to update package regarding new SignalR/SignalR version?
Please update us with a release date, appreciated!

**Comment by gregveres** [comment]
Check out this fork. It was forked from here because the maintainer of this package has vanished.

https://github.com/cojamru/signalr-no-jquery

It might not have the fixe for Chrome 88, but it is the most maintained version I am aware of.

**Comment by DVLP** [comment]
Fixed with 2.4.3
